theme: jekyll-theme-cayman
title: How to host a resume

#this solution to make the tables work is found here 
# https://stackoverflow.com/questions/26844701/lists-in-markdown-table-with-jekyll
markdown: kramdown
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data
